### ISSUE TITLE
Provide a basic example of locally converting a NetCDF to a Zarr

### ISSUE THREAD

**Issue by Faolain** [Arbol-Project/zarr-climate-etl-ipfs#3]
**Motivation**
As of right now the documentation is extremely comprehensive and very extensive (which is a good thing!). However this could be overwhelming for someone just trying to convert some netcdf files they have they wish to put on IPFS as a zarr. For someone not familiar with our setup and has some netcdf files maybe a basic example of converting a rump netcdf could be worthwhile to have in the documentation. 

Aka example small netcdf here's how to use the generate_zarr script (or another) and here's the output. Initially could be a series of command line inputs which if time permits can be a Jupyter notebook. Ideally a small test netcdf should be included in the repo that a user can run and replace with their own netcdf. 

In other words, 

```
$ ls 
generate_zarr_from_netcdf.py 
.....
test.nc

$ ./generate_zarr_from_netcdf.py test.nc
Added to IPFS
IPNS HASH: bafyreibnfezcttd5zcjlp74lohe3ieqmtc73cybvfhh6ugzusxc2yi6ky4

$ ipython
> import xarray, ipldstore
> mapper = ipldstore.get_ipfs_mapper()
> mapper.set_root("bafyreibnfezcttd5zcjlp74lohe3ieqmtc73cybvfhh6ugzusxc2yi6ky4") # Same Hash from above
> xarray.open_zarr(mapper, consolidated=False)
<xarray.Dataset>
Dimensions:    (latitude: 120, longitude: 300, time: 5736)
Coordinates:
  * latitude   (latitude) float32 20.12 20.38 20.62 20.88 ... 49.38 49.62 49.88
  * longitude  (longitude) float32 -129.9 -129.6 -129.4 ... -55.62 -55.38 -55.12
  * time       (time) datetime64[ns] 2007-01-01 2007-01-02 ... 2022-09-14
Data variables:
  precip     (time, latitude, longitude) float32 dask.array<chunksize=(1769, 24, 24), meta=np.ndarray>
...

```

**User Story:**
As a new user to the dClimate ecosystem I want to be easily able to convert my netcdf files to zarrs on IPFS by following an example.

**Acceptance Criteria:**
- [ ] Include Test netcdf file in the root of repo 
- [ ] Provide Jupyter notebook instructions leveraging the already existing Jupyter Notebooks to convert netcdf to zarr on ipfs(that install IPFS on behalf of the user) original: https://colab.research.google.com/drive/1KsMC64bb1HpQPF2hi7LP96ZzKlaULzOH#scrollTo=5J1WMvwA7azD&forceEdit=true&sandboxMode=true and fork by Adam living on github which does some visualization https://gist.github.com/adamfil/e820881c453638559bac13c718a33528 

**Additional Information:**
Should be something more or less like this (just with the addition of including adding to ipfs via ipldstore after)

![image](https://user-images.githubusercontent.com/9613083/228007790-a639775b-a3fc-40a9-a32e-dc9cba567830.png)
![image](https://user-images.githubusercontent.com/9613083/228007824-5d2ad03e-c399-40e4-bb4d-631a54992198.png)

**Comment by rbanick** [comment]
Resolved by v0.2.0 release # @
