### ISSUE TITLE
Additional package install instructions - particularly for MacOS install

### ISSUE THREAD

**Issue by clemp** [Arbol-Project/zarr-climate-etl-ipfs#4]
In addition to the Python requirements I also needed to install a few extra packages on my MacOS computer using `brew`.

`sudo apt install cod` I instead ran `brew install cdo`

`sudo apt install libjpeg-dev` I instead ran `brew install jpeg`

`sudo apt install libjpeg-dev` I instead ran `brew install gdal` 

`sudo apt install netcdf-bin` I instead ran `brew install netcdf`

` sudo apt install libeccodes0` I instead ran `brew install eccodes`

After setting up my MacOS (on the Apple M2 Silicon chip) I was able to run parses of `NetCDF` files to `zarr`

**Comment by rbanick** [comment]
Addressed by #5 , can you please review and merge @clemp

**Comment by clemp** [comment]
Done
